default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: ../../shared/db/production.sqlite3

sandbox:
  <<: *default
  database: ../../shared/db/sandbox.sqlite3
