# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd183e4a2092903e3ce09ec8053a3dc75359051345fad4c7905c5581412c96ba1c2961df64de2c811f3df647cad20d1a66b21c3f88aa66a03f0bc5cb0c93592b

test:
  secret_key_base: 09045a3b2a30b9be4ecbc1ba46104e531646ea4338942d154c19091eb27fdec10b752b0f37c847b3c98a5d40338a18e30b55e240ff1c7d34fde2ace9cd6db4f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
